version: '3'

services:
  gdbserver:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: g2p_dev
    security_opt:
      - seccomp:unconfined
    container_name: gtop
    ports:
      - "7778:22"
    volumes:
      - .:/home/debugger/g2pDocker
    working_dir: /home/debugger/g2pDocker
    hostname: debug